name: Multi-Triggres

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:        
    inputs:                 
      environment:
        description: 'Which environment to deploy to?'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  Multi-Triggres:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo 'Hello from GitHub Actions'

      - name: List the Hidden Files
        run: ls -a

      - name: disk space 
        run: df
