name: My First Workflow

on:
  push:
    branches:
      - main

jobs:
  Welocome-All:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo 'Welcome To All Devops Classes & Bhuvanesh Student'

      - name: Print the date
        run: date

      - name: Directory finds
        run: pwd
