name: Multi-Triggres

 on:
  push:
    branches: [main]
  schedule:
      - cron:'1 * * * *'
 jobs:
  Multi-Triggres:
    runs-on: ubuntu-latest
    steps:
      - name: create a file
        run: echo 'Hello.txt'

      - name: List the Hidden Files
        run: ls -a

      - name: disk space 
        run: df     
