name: Multi-Triggres

on:
  push:
    branches: [main]
  schedule:
      - cron:'1 * * * *'

  jobs:
    Multi-Triggres:
    runs-on: ubuntu-latest
    steps:
      - name: create a file
        run: touch deploy   
