name: cron

on:
  push:
    branches: [main]
  schedule:
      - cron:'1 * * * *'

jobs:
    cron:
       runs-on: ubuntu-latest
    steps:
      - name: create a file
        run: touch deploy  
